language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4.3

before_install:
  - sudo apt-get update -q -y
  - sudo apt-get install libnetcdf-dev -y

script:
  - go install -v ./...
  - go test -v ./...
  - ApplicationTest.exe --files=Data/csp00101.cnv